### ISSUE TITLE
[Keva] Scaling Issue

### ISSUE THREAD

**Issue by tuhuynh27** [tuhuynh27/jiny#63]
Currently, Keva is a key-value store that can only allow single-thread read/write on it (because the read/write lock is not implemented in the store).

> **Why not multi-thread allowed? Why there's no lock?**
> Writing a multi-threaded store can be trickier. Sometimes multi-threading may not work, locks can block other threads.
> Lock-free store can prevent any lock contention and thus memory access can be faster, and locking overhead is avoided.

Thus in nature, it cannot utilize all CPU-cores (because only one thread allowed read/write to the store - similar to Redis), we need to run multiple instances of Keva Store to be able to utilize multi-core CPU.

We can implement a client (or server) sharding using [Consistent Hashing](https://en.wikipedia.org/wiki/Consistent_hashing), that will receive the key and then use Consistent Hashing to find the accordant Keva Store server to send the request to.

Like this:

`keva-shard-config.yml`

```yaml
keva-server-list:
  server1: 10.244.56.1:7777
  server2: 10.244.57.1:7777
  server3: 10.244.58.1:7777
  server4: 10.244.59.1:7777
```

(We don't need to care about high availability now)
